{{- $def := .Values.vmDefaults }}
{{- range $edvc, $edv := .Values.externalDataVolumes }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ $edv.name }}
  namespace: {{ coalesce $edv.namespace $def.externalDataVolumeNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  {{- if $def.externalDataVolumeAnnodations }}
    {{ $def.externalDataVolumeAnnodations | toYaml }}
  {{- end }}
  {{- if $edv.annotations }}
    {{ $edv.annotations |toYaml }}
  {{- end }}
spec:
  source:
    {{- if eq (coalesce $edv.type $def.dataVolumeType) "registry"}}
    registry:
      url: {{ $edv.url }}
      {{- if $edv.registryCredentialsSecret }}
      secretRef: {{ $edv.registryCredentialsSecret }}
      {{- end }}
    {{ else if eq (coalesce $edv.type $def.dataVolumeType) "http"}}
    http:
      url: {{ $edv.url }}
    {{- end }}
  {{- if $edv.size }}
  storage:
    resources:
      requests:
        storage: {{ $edv.size }}
  {{- end }}
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: {{ $edv.name }}
  namespace: {{ coalesce $edv.namespace $def.externalDataVolumeNamespace }}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    pvc:
      name: {{ $edv.name }}
      namespace: {{ coalesce $edv.namespace $def.externalDataVolumeNamespace }}
{{- end }}

{{- if gt ( len .Values.externalDataVolumes ) 0 }} # this is needed for DataSources to clone DataVolumes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: os-images.kubevirt.io:view
  {{- if (coalesce $def.externalDataVolumeNamespace nil) }} # FIXME this will not create Roles for the namespaces of individual datavolumes, just the default namespace
  namespace: {{ coalesce $def.externalDataVolumeNamespace }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes/source
  verbs:
  - create
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datasources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - dataimportcrons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: os-images.kubevirt.io:view
  {{- if (coalesce $def.externalDataVolumeNamespace nil) }} # FIXME see above
  namespace: {{ coalesce $def.externalDataVolumeNamespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: os-images.kubevirt.io:view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
{{- end }}
